- biome: Meadows
  environments:
  - environment: Clear
    weight: 5
  - environment: Rain
    weight: 0.2
  - environment: Misty
    weight: 0.2
  - environment: ThunderStorm
    weight: 0.2
  - environment: LightRain
    weight: 0.2
  mapColor:
    r: 0.573
    g: 0.655
    b: 0.361
    a: 1
  musicDay: meadows
- biome: BlackForest
  environments:
  - environment: DeepForest Mist
    weight: 2
  - environment: Rain
    weight: 0.1
  - environment: Misty
    weight: 0.1
  - environment: ThunderStorm
    weight: 0.1
  color:
    b: 1
  mapColor:
    r: 0.42
    g: 0.455
    b: 0.247
    a: 1
  musicDay: blackforest
  musicNight: blackforest
- biome: Swamp
  environments:
  - environment: SwampRain
  color:
    r: 1
  mapColor:
    r: 0.639
    g: 0.447
    b: 0.345
    a: 1
  musicDay: swamp
  musicNight: swamp
- biome: Mountain
  environments:
  - environment: SnowStorm
  - environment: Snow
    weight: 5
  color:
    g: 1
  mapColor:
    r: 1
    g: 1
    b: 1
    a: 1
  musicDay: mountain
  musicNight: mountain
- biome: DeepNorth
  environments:
  - environment: Twilight_SnowStorm
    weight: 0.5
  - environment: Twilight_Snow
  - environment: Twilight_Clear
  color:
    g: 1
  mapColor:
    r: 1
    g: 1
    b: 1
    a: 1
- biome: Plains
  environments:
  - environment: Heath clear
    weight: 2
  - environment: Misty
    weight: 0.4
  - environment: LightRain
    weight: 0.4
  color:
    a: 1
  mapColor:
    r: 0.906
    g: 0.671
    b: 0.47
    a: 1
  musicDay: plains
  musicNight: plains
- biome: AshLands
  environments:
  - environment: Ashrain
  color:
    r: 1
    a: 1
  mapColorMultiplier: 0.5
  mapColor:
    r: 0.69
    g: 0.192
    b: 0.192
    a: 1
  musicMorning: '-'
  musicEvening: '-'
- biome: Ocean
  environments:
  - environment: Rain
    weight: 0.1
  - environment: LightRain
    weight: 0.1
  - environment: Misty
    weight: 0.1
  - environment: Clear
  - environment: ThunderStorm
    weight: 0.1
  mapColor:
    r: 1
    g: 1
    b: 1
    a: 1
- biome: Mistlands
  environments:
  - environment: DeepForest Mist
    weight: 1.0
  - environment: Rain
    weight: 0.2
  - environment: Misty
    weight: 0.5
  - environment: ThunderStorm
    weight: 0.1
  color:
    b: 1
    a: 1
  mapColor:
    r: 0.2
    g: 0.2
    b: 0.2
    a: 1
- biome: darkmeadows
  name: Dark Meadows
  terrain: meadows
  environments:
  - environment: DeepForest Mist
    weight: 1.0
  - environment: Rain
    weight: 0.2
  - environment: Misty
    weight: 0.5
  - environment: ThunderStorm
    weight: 0.1
  color:
    b: 1
  mapColor:
    r: 0.20
    g: 0.20
    b: 0.20
    a: 1
  musicDay: meadows
- biome: darkblackforest
  name: Dark Black Forest
  terrain: blackforest
  environments:
  - environment: DeepForest Mist
    weight: 1.0
  - environment: Rain
    weight: 0.2
  - environment: Misty
    weight: 0.5
  - environment: ThunderStorm
    weight: 0.1
  color:
    b: 1
  mapColor:
    r: 0.2
    g: 0.25
    b: 0.12
    a: 1
  musicDay: blackforest
  musicNight: blackforest
- biome: darkswamp
  name: Dark Swamp
  terrain: swamp
  environments:
  - environment: SwampRain
  color:
    r: 1
  mapColor:
    r: 1.7
    g: 1.5
    b: 1.4
    a: 1
  musicDay: swamp
  musicNight: swamp
- biome: darkmountain
  name: Dark Mountain
  terrain: mountain
  altitudeMultiplier: 1.3
  environments:
  - environment: SnowStorm
  color:
    g: 1
  mapColor:
    r: 0.5
    g: 0.5
    b: 0.5
    a: 1
  musicDay: mountain
  musicNight: mountain
- biome: darkplains
  name: Dark Plains
  terrain: plains
  environments:
  - environment: DeepForest Mist
    weight: 0.1
  - environment: Rain
    weight: 0.1
  - environment: Misty
    weight: 0.1
  - environment: ThunderStorm
    weight: 0.1
  color:
    a: 1
  mapColor:
    r: 0.6
    g: 0.5
    b: 0.3
    a: 1
  musicDay: plains
  musicNight: plains
- biome: darkdeepnorth
  name: Dark Deep North
  terrain: deepnorth
  environments:
  - environment: Twilight_SnowStorm
    weight: 0.5
  color:
    g: 1
  mapColor:
    r: 0.5
    g: 0.5
    b: 0.5
    a: 0.5
- biome: darkmistlands
  name: Dark Mistlands
  terrain: mistlands
  environments:
  - environment: DeepForest Mist
    weight: 1.0
  - environment: Rain
    weight: 0.2
  - environment: Misty
    weight: 0.5
  - environment: ThunderStorm
    weight: 0.1
  color:
    b: 1
    a: 1
  mapColor:
    r: 0.15
    g: 0.15
    b: 0.15
    a: 1
  musicMorning: '-'
  musicEvening: '-'
- biome: darkashlands
